apiVersion: v1
kind: Pod
metadata:
  name: knb-cli
  labels : {
     knb-runid: tcp-crr-calico-ebpf-32-20250623111847,
     role: cli,
  }
spec:
  restartPolicy: Never
  
  affinity:
     podAntiAffinity:
         requiredDuringSchedulingIgnoredDuringExecution:
         - labelSelector:
              matchExpressions:
              - key: role
                operator: In
                values:
                - srv
           topologyKey: "kubernetes.io/hostname"

  containers:
  - name: netperf-cli
    image: cilium/kubenetbench
    command: ["scripts/duper_netperf"]
    args : [
        # initial args
        "32",
        "-l", "300", # timeout
        "-j", # enable additional statistics
        "-H", "10.233.227.141",
        "-t", "tcp_crr", # testname
        "--",
        # Benchmark args
        "-P", ",8000", # data connection port
        "-k", "THROUGHPUT,THROUGHPUT_UNITS,THROUGHPUT_CONFID,PROTOCOL,ELAPSED_TIME,LOCAL_SEND_CALLS,LOCAL_BYTES_PER_SEND,LOCAL_RECV_CALLS,LOCAL_BYTES_PER_RECV,REMOTE_SEND_CALLS,REMOTE_BYTES_PER_SEND,REMOTE_RECV_CALLS,REMOTE_BYTES_PER_RECV,LOCAL_SYSNAME,LOCAL_RELEASE,LOCAL_VERSION,LOCAL_MACHINE,REMOTEL_SYSNAME,REMOTEL_RELEASE,REMOTEL_VERSION,REMOTEL_MACHINE,COMMAND_LINE,LOCAL_TRANSPORT_RETRANS,REMOTE_TRANSPORT_RETRANS,TRANSACTION_RATE,P50_LATENCY,P90_LATENCY,RT_LATENCY,MEAN_LATENCY,STDEV_LATENCY,REQUEST_SIZE,RESPONSE_SIZE,BURST_SIZE",
    ]

