apiVersion: v1
kind: Pod
metadata:
  name: knb-srv
  labels : {
    knb-sessid: calico-iptables,
    knb-runid: tcp-stream-32-20250603144327,
    role: srv,
  }
spec:
  
  containers:
  - name: netperf-srv
    image: cilium/kubenetbench
    command: ["netserver"]
    args : [
        "-D", # dont daemonize
    ]

